' ******************************************************************************
' swxJRNL.swj - journal recorded on 03/06/13 by eng2
' *****************************************************************************
Dim swApp As Object
Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long
Dim FeatureData As Object
Dim Feature As Object
Dim Component As Object
Sub main()

Set swApp = Application.SldWorks

Set Part = swApp.OpenDoc6 ("C:\Documents and Settings\eng2\My Documents\GitHub\FiberHolder\Quick Release Fiber Holder V4.SLDASM", 2, 0, "", longstatus, longwarnings)
Set Part = swApp.ActivateDoc ("Quick Release Fiber Holder V4.SLDASM")
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
Part.ActiveView().RotateAboutCenter 0.00451564, -0.00728184
Part.ActiveView().RotateAboutCenter 0.0722502, -0.429628
Part.ActiveView().RotateAboutCenter 0.00903127, -0.320401
Part.ActiveView().RotateAboutCenter 0, -0.269428
Part.ActiveView().RotateAboutCenter -0.049672, -0.342246
Part.ActiveView().RotateAboutCenter -0.0451564, -0.305837
Part.ActiveView().RotateAboutCenter -0.0270938, -0.131073
Part.ActiveView().RotateAboutCenter -0.0406407, -0.123791
Part.ActiveView().RotateAboutCenter -0.0632189, -0.0946639
Part.ActiveView().RotateAboutCenter -0.0767658, -0.0728184
Part.ActiveView().RotateAboutCenter -0.049672, -0.043691
Part.ActiveView().RotateAboutCenter -0.0225782, -0.0145637
Part.ActiveView().RotateAboutCenter 0, 0.00728184
Part.ActiveView().RotateAboutCenter 0.1445, 0.0801002
Part.ActiveView().RotateAboutCenter 0.302548, 0.27671
Part.ActiveView().RotateAboutCenter 0.302548, 0.254864
Part.ActiveView().RotateAboutCenter 0.189657, 0.0946639
Part.ActiveView().RotateAboutCenter 0.0857971, 0.0145637
Part.ActiveView().RotateAboutCenter 0.0270938, 0
Part.ActiveView().RotateAboutCenter 0.0135469, 0.00728184
Part.ActiveView().RotateAboutCenter 0.0451564, 0.0291273
Part.ActiveView().RotateAboutCenter 0.00903127, 0.00728184
Part.ActiveView().RotateAboutCenter -0.0361251, 0.101946
Part.ActiveView().RotateAboutCenter -0.099344, 0.1602
Part.ActiveView().RotateAboutCenter -0.10386, 0.0582547
Part.ActiveView().RotateAboutCenter -0.0948284, 0.0946639
Part.ActiveView().RotateAboutCenter -0.0677345, 0.0728184
Part.ActiveView().RotateAboutCenter -0.0767658, 0.0728184
Part.ActiveView().RotateAboutCenter -0.0722502, 0.0145637
Part.ActiveView().RotateAboutCenter -0.0316095, 0.00728184
Part.ActiveView().RotateAboutCenter -0.00451564, 0
swApp.ActiveDoc.ActiveView.FrameState = 1
' MSGBOX
' C:\Documents and Settings\eng2\My Documents\GitHub\FiberHolder\Outer Clamp Latch.SLDPRT has one or more update errors.  Save anyway?

Part.Save2 FALSE
swApp.ExitApp
End Sub
