' ******************************************************************************
' swxJRNL.swj - journal recorded on 02/26/13 by eng2
' *****************************************************************************
Dim swApp As Object
Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long
Dim FeatureData As Object
Dim Feature As Object
Dim Component As Object
Sub main()

Set swApp = Application.SldWorks

Set Part = swApp.OpenDoc6 ("C:\Documents and Settings\eng2\My Documents\GitHub\FiberHolder\Quick Release Fiber Holder V4.SLDASM", 2, 0, "", longstatus, longwarnings)
Set Part = swApp.ActivateDoc ("Quick Release Fiber Holder V4.SLDASM")
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
boolstatus = Part.Extension.SelectByID("", "FACE", 0.008376704004547, 0.006697565783099, 0.0060959999999, False, 0, Nothing)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID("Base-1@Quick Release Fiber Holder V4", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Base-1@Quick Release Fiber Holder V4", "COMPONENT", 0, 0, 0, False, 0, Nothing)
Part.ClearSelection2 True
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
boolstatus = Part.Extension.SelectByID("", "FACE", 0.001088823111104, 0.0008001679296399, 0.004898823110921, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Inner Clamp-1@Quick Release Fiber Holder V4", "COMPONENT", 0, 0, 0, False, 0, Nothing)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID("Outer Clamp-1@Quick Release Fiber Holder V4", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Outer Clamp-1@Quick Release Fiber Holder V4", "COMPONENT", 0, 0, 0, False, 0, Nothing)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID("Outer Clamp Latch-1@Quick Release Fiber Holder V4", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Inner Clamp Latch-1@Quick Release Fiber Holder V4", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Inner Clamp Latch-1@Quick Release Fiber Holder V4", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Outer Clamp Latch-1@Quick Release Fiber Holder V4", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Outer Clamp Latch-1@Quick Release Fiber Holder V4", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Inner Clamp-1@Quick Release Fiber Holder V4", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Inner Clamp Latch-1@Quick Release Fiber Holder V4", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Outer Clamp Latch-1@Quick Release Fiber Holder V4", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Outer Clamp Latch-1@Quick Release Fiber Holder V4", "COMPONENT", 0, 0, 0, False, 0, Nothing)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID("Inner Clamp Latch-1@Quick Release Fiber Holder V4", "COMPONENT", 0, 0, 0, False, 0, Nothing)
Part.ClearSelection2 True
' MSGBOX
' Quick Release Fiber Holder V4 has not been rebuilt successfully since the last feature change or an externally referenced model has changed.
' 	It is safest to rebuild before saving.
' 		Rebuild now?

Part.SaveAs2 "C:\Documents and Settings\eng2\Desktop\fiber holder-magnetic.jpg", 0, TRUE, FALSE
' MSGBOX
' Save changes to Quick Release Fiber Holder V4.SLDASM?

Part.Save2 FALSE
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ExitApp
End Sub
