' ******************************************************************************
' swxJRNL.swj - journal recorded on 03/19/13 by eng2
' *****************************************************************************
Dim swApp As Object
Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long
Dim FeatureData As Object
Dim Feature As Object
Dim Component As Object
Sub main()

Set swApp = Application.SldWorks

Set Part = swApp.OpenDoc6 ("C:\Documents and Settings\eng2\My Documents\GitHub\FiberHolder\Quick Release Fiber Holder V4.SLDASM", 2, 0, "", longstatus, longwarnings)
Set Part = swApp.ActivateDoc ("Quick Release Fiber Holder V4.SLDASM")
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
Part.ActiveView().RotateAboutCenter 0.0135469, 0
Part.ActiveView().RotateAboutCenter 0.108375, 0
Part.ActiveView().RotateAboutCenter 0.121922, 0
Part.ActiveView().RotateAboutCenter 0.099344, 0
Part.ActiveView().RotateAboutCenter 0.0857971, -0.0145637
Part.ActiveView().RotateAboutCenter 0.121922, -0.043691
Part.ActiveView().RotateAboutCenter 0.0857971, -0.043691
Part.ActiveView().RotateAboutCenter 0.0812815, -0.0218455
Part.ActiveView().RotateAboutCenter 0.0903127, -0.0145637
Part.ActiveView().RotateAboutCenter 0.0632189, 0
Part.ActiveView().RotateAboutCenter 0.0406407, 0
Part.ActiveView().RotateAboutCenter 0.0316095, 0
Part.ActiveView().RotateAboutCenter 0.0270938, -0.0145637
Part.ActiveView().RotateAboutCenter 0.00903127, -0.0145637
Part.ActiveView().RotateAboutCenter -0.00451564, -0.0145637
Part.ActiveView().RotateAboutCenter -0.0406407, -0.00728184
Part.ActiveView().RotateAboutCenter -0.126438, 0.0145637
Part.ActiveView().RotateAboutCenter -0.117407, 0.043691
Part.ActiveView().RotateAboutCenter -0.099344, 0.0655365
Part.ActiveView().RotateAboutCenter -0.153532, 0.0946639
Part.ActiveView().RotateAboutCenter -0.149016, 0.087382
Part.ActiveView().RotateAboutCenter -0.167079, 0.0582547
Part.ActiveView().RotateAboutCenter -0.112891, 0.00728184
Part.ActiveView().RotateAboutCenter -0.180625, 0.0509729
Part.ActiveView().RotateAboutCenter -0.126438, 0.00728184
Part.ActiveView().RotateAboutCenter -0.0722502, 0.0145637
Part.ActiveView().RotateAboutCenter 0.0135469, 0
Part.ActiveView().RotateAboutCenter 0.099344, -0.0509729
Part.ActiveView().RotateAboutCenter 0.135469, -0.0509729
Part.ActiveView().RotateAboutCenter 0.0677345, -0.0218455
Part.ActiveView().RotateAboutCenter 0.00451564, 0
Part.ActiveView().RotateAboutCenter 0.0135469, -0.0218455
boolstatus = Part.Extension.SelectByID("", "FACE", -0.008026607589045, 0.009482907982914, 0.001468270238121, False, 0, Nothing)
Part.TranslateComponent
' MSGBOX
' C:\Documents and Settings\eng2\My Documents\GitHub\FiberHolder\Quick Release Fiber Holder V4.SLDASM has not been rebuilt successfully since the last feature change or an externally referenced model has changed.
' 	It is safest to rebuild before saving.
' 		Rebuild now?

' MSGBOX
' Some of the models referenced in this document have been modified.  They must be saved when the document is saved.
' 		Save the document and the referenced models now?

Part.Save2 FALSE
swApp.SetUserPreferenceIntegerValue swAutoSaveInterval , 10
Part.SetUserPreferenceIntegerValue swUnitsLinearDecimalPlaces , 2
Part.ActiveView().RotateAboutCenter 0.00903127, -0.00728184
Part.ActiveView().RotateAboutCenter 0.0722502, -0.145637
Part.ActiveView().RotateAboutCenter 0.0587033, -0.174764
Part.ActiveView().RotateAboutCenter 0.0632189, -0.167482
Part.ActiveView().RotateAboutCenter 0.0270938, -0.0582547
Part.ActiveView().RotateAboutCenter 0, 0.313119
Part.ActiveView().RotateAboutCenter 0.0225782, 0.961203
Part.ActiveView().RotateAboutCenter 0.0361251, 0.298555
Part.ActiveView().RotateAboutCenter 0, 0.0218455
Part.ActiveView().RotateAboutCenter -0.00903127, 0.0364092
Part.ActiveView().RotateAboutCenter -0.0135469, 0.043691
Part.ActiveView().RotateAboutCenter -0.0225782, 0.0509729
Part.ActiveView().RotateAboutCenter -0.0406407, 0.043691
Part.ActiveView().RotateAboutCenter -0.0135469, 0.0509729
Part.ActiveView().RotateAboutCenter 0.00451564, 0.0291273
Part.ActiveView().RotateAboutCenter 0.00451564, 0.0655365
Part.ActiveView().RotateAboutCenter -0.00451564, 0.0509729
Part.ActiveView().RotateAboutCenter -0.00451564, 0
Part.ActiveView().RotateAboutCenter -0.0225782, 0.00728184
Part.ActiveView().RotateAboutCenter -0.00451564, 0
Part.ActiveView().RotateAboutCenter 0.00451564, -0.0145637
Part.ActiveView().RotateAboutCenter 0.0316095, -0.174764
Part.ActiveView().RotateAboutCenter 0.0135469, -0.225737
Part.ActiveView().RotateAboutCenter -0.0541876, -0.371374
Part.ActiveView().RotateAboutCenter -0.0722502, -0.71362
Part.ActiveView().RotateAboutCenter 0.00903127, -0.240301
Part.ActiveView().RotateAboutCenter 0.00903127, -0.109228
Part.ActiveView().RotateAboutCenter -0.0225782, -0.0655365
Part.ActiveView().RotateAboutCenter -0.049672, -0.0728184
Part.ActiveView().RotateAboutCenter -0.10386, -0.0946639
Part.ActiveView().RotateAboutCenter -0.0767658, -0.0582547
Part.ActiveView().RotateAboutCenter -0.0677345, -0.043691
Part.ActiveView().RotateAboutCenter -0.0632189, -0.0218455
Part.ActiveView().RotateAboutCenter -0.0632189, 0.0218455
Part.ActiveView().RotateAboutCenter -0.0451564, 0.0291273
Part.ActiveView().RotateAboutCenter -0.117407, 0.0655365
Part.ActiveView().RotateAboutCenter -0.0541876, 0.043691
Part.ActiveView().RotateAboutCenter -0.00451564, 0
Part.ActiveView().RotateAboutCenter 0.049672, 0.0364092
Part.ActiveView().RotateAboutCenter 0.0135469, 0.0218455
Part.ActiveView().RotateAboutCenter 0.049672, -0.0145637
Part.ActiveView().RotateAboutCenter 0.0270938, -0.0145637
Part.ActiveView().RotateAboutCenter 0.0180625, -0.0145637
Part.ActiveView().RotateAboutCenter 0.00451564, 0
swApp.ActiveDoc.ActiveView.FrameState = 1
Part.ClearSelection2 True
swApp.ExitApp
End Sub
